global:
  message: Welcome to customer service dev env
server:
  port: 8081
message: Hellow fro Dev!
spring: 
  datasource:
    url: jdbc:mysql://localhost:3306/customer_dev
    username: root
    password: pass
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
