global:
  message: Welcome to customer service prod env
server:
  port: 8083
message: Hellow fro Prod!
spring: 
  datasource:
    url: jdbc:mysql://localhost:3306/customer_prod
    username: root
    password: pass
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
