global:
  message: Welcome to order service prod env
server:
  port: 8085
message: Hellow from prod!
spring: 
  datasource:
    url: jdbc:mysql://localhost:3306/order_prod
    username: root
    password: pass
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
